wandb_version: 1

example_metric:
  desc: null
  value: Example Value!
_wandb:
  desc: null
  value:
    code_path: code/main_flow.py
    python_version: 3.9.6
    cli_version: 0.16.6
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718650806.0
    t:
      1:
      - 13
      - 55
      2:
      - 13
      - 55
      3:
      - 16
      - 23
      4: 3.9.6
      5: 0.16.6
      8:
      - 4
      - 5
      13: darwin-arm64
